### PR TITLE
Add support for Overlays

### PR DESCRIPTION
**Pull request by ricohumme**
This is something that was missing.

### CODE REVIEW

**Comment by ricohumme** [comment]
@Dean177 Could you review this and get this merged? I tried importing it from my own repo but that fails due to the project being one level deeper. Thanks in advance

**Comment by Dean177** [comment]
Thanks @ricohumme

**Comment by ricohumme** [comment]
@Dean177 do you have any suggestion for me on how to use your version on github? On npmjs this version is not current.
thnx in advance

**Comment by ricohumme** [comment]
ping @Dean177

**Pull request merged**
